server:
  port: 8763
  
spring:
  application:
    name: hystrix-service
    
    
hystrix:
  dashboard:
    proxy-stream-allow-list: "*"   
  
#Eureka Server Register
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/  
